// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated at 2023-08-19 14:01:12.1105135 +0800 CST m=+0.173155501

package col

import (
	"github.com/michaelzx/pgx-z/examples/tmp/model"
	"github.com/michaelzx/pgx-z/pgxz"
)

type ding_dept struct {
	pgxz.Col
}

func DingDept(m *model.DingDept) *ding_dept {
	c := new(ding_dept)
	c.Init()
	if m != nil {
		c.SetIfNotNil("id", m.Id)
		c.SetIfNotNil("pid", m.Pid)
		c.SetIfNotNil("title", m.Title)
	}
	return c
}

const tableNameDingDept = "ding_dept"

func (ding_dept) TableName() string {
	return tableNameDingDept
}

func (r *ding_dept) Keys() []string {
	return []string{
		"id", "pid", "title",
	}
}
func (r *ding_dept) Id(v int64) *ding_dept {
	r.Set("id", v)
	return r
}
func (r *ding_dept) Pid(v int64) *ding_dept {
	r.Set("pid", v)
	return r
}
func (r *ding_dept) Title(v string) *ding_dept {
	r.Set("title", v)
	return r
}
