// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated at 2023-08-19 14:01:12.1083701 +0800 CST m=+0.171012101

package col

import (
	"github.com/michaelzx/pgx-z/examples/tmp/model"
	"github.com/michaelzx/pgx-z/pgxz"
)

type domain struct {
	pgxz.Col
}

func Domain(m *model.Domain) *domain {
	c := new(domain)
	c.Init()
	if m != nil {
		c.SetIfNotNil("tag", m.Tag)
		c.SetIfNotNil("leaders", m.Leaders)
		c.SetIfNotNil("configs", m.Configs)
	}
	return c
}

const tableNameDomain = "domain"

func (domain) TableName() string {
	return tableNameDomain
}

func (r *domain) Keys() []string {
	return []string{
		"tag", "leaders", "configs",
	}
}
func (r *domain) Tag(v string) *domain {
	r.Set("tag", v)
	return r
}
func (r *domain) Leaders(v []string) *domain {
	r.Set("leaders", v)
	return r
}
func (r *domain) Configs(v []byte) *domain {
	r.Set("configs", v)
	return r
}
