// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated at 2023-08-19 14:01:12.1089104 +0800 CST m=+0.171552401

package col

import (
	"github.com/michaelzx/pgx-z/examples/tmp/model"
	"github.com/michaelzx/pgx-z/pgxz"
)

type team struct {
	pgxz.Col
}

func Team(m *model.Team) *team {
	c := new(team)
	c.Init()
	if m != nil {
		c.SetIfNotNil("no", m.No)
		c.SetIfNotNil("title", m.Title)
	}
	return c
}

const tableNameTeam = "team"

func (team) TableName() string {
	return tableNameTeam
}

func (r *team) Keys() []string {
	return []string{
		"no", "title",
	}
}
func (r *team) No(v string) *team {
	r.Set("no", v)
	return r
}
func (r *team) Title(v string) *team {
	r.Set("title", v)
	return r
}
