// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated at 2023-08-19 14:01:12.1078288 +0800 CST m=+0.170470801

package model

// Domain mapped from table <ding_dept>
type DingDept struct {
	Id    int64  `db:"id" udt:"int8" json:"id"`          // 部门id
	Pid   int64  `db:"pid" udt:"int8" json:"pid"`        // 上级部门id
	Title string `db:"title" udt:"varchar" json:"title"` // 部门名称
}

const TableNameDingDept = "ding_dept"

// TableName DingDept's table name
func (DingDept) TableName() string {
	return TableNameDingDept
}
