// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated at 2023-08-19 14:01:12.0936318 +0800 CST m=+0.156273801

package model

// Domain mapped from table <domain>
type Domain struct {
	Tag     string   `db:"tag" udt:"varchar" json:"tag"`          // 领域标签
	Leaders []string `db:"leaders" udt:"_varchar" json:"leaders"` // 领域领导
	Configs []byte   `db:"configs" udt:"jsonb" json:"configs"`    // 领域配置
}

const TableNameDomain = "domain"

// TableName Domain's table name
func (Domain) TableName() string {
	return TableNameDomain
}
