// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated by pgx-z. DO NOT EDIT.
// Code generated at 2023-08-19 14:01:12.106151 +0800 CST m=+0.168793001

package model

// Domain mapped from table <team>
type Team struct {
	No    string `db:"no" udt:"varchar" json:"no"`       // 编号
	Title string `db:"title" udt:"varchar" json:"title"` // 名称
}

const TableNameTeam = "team"

// TableName Team's table name
func (Team) TableName() string {
	return TableNameTeam
}
